### ISSUE TITLE
Next.js -> React.js + Vite, test環境にvitestに変更する

### ISSUE THREAD

**Issue by re-taro** [suzuka-kosen-festa/2022-HP#175]
- ハイドレーションエラーがNext.jsのserver side side rendering(SG)に起因するから
  - CSS in JSを辞めるという手もあるが修正は @re-taro になるのでやりたくない。しろと言われればしますが
- Vercelに投げるつもりがない
- 現状、Next.js固有の機能が使われていない(API route, SG, SSRなど)
  - font optimization, image optimizationはVercelに投げないと効果がないので

**Comment by re-taro** [comment]
ここに @Bayathy がメンションされているのは仮に載せ替えを検討する場合APIとして返して欲しいデータがいくつかあるためです。なのでそういった意味でもメンションしています。

**Comment by re-taro** [comment]
議論の期限は9/20とします。

**Comment by Sansai-snct** [comment]
Nextの恩恵を受けられる場面が少ないので、React移行に賛成です

**Comment by re-taro** [comment]
了解です。 @Bayathy のタスク次第なのですがどうしましょう？

**Comment by Bayathy** [comment]
大体何日までに作ればいいですか？

**Comment by re-taro** [comment]
10月頭までにですかね～

**Comment by Bayathy** [comment]
了解です
